export const ErrorCode = {
  USER_ALREADY_EXISTS: 'AUTH-001',
  INVALID_CREDENTIALS: 'AUTH-002',
  PASSWORD_NOT_MATCHING: 'AUTH-003',

  PRODUCT_NOT_FOUND: 'PRODUCT-001',
  PRODUCT_ALREADY_EXISTS: 'PRODUCT-002',

  SKU_NOT_FOUND: 'INVENTORY-001',
  INSUFFICIENT_STOCK: 'INVENTORY-002',
  INVALID_STOCK_QUANTITY: 'INVENTORY-003',
};
