export const ErrorCode = {
  PRODUCT_NOT_FOUND: 'PRODUCT-001',

  SKU_NOT_FOUND: 'INVENTORY-001',
  INSUFFICIENT_STOCK: 'INVENTORY-002',
  INVALID_STOCK_QUANTITY: 'INVENTORY-003',

  USER_ALREADY_EXISTS: 'AUTH-001',
  PASSWORD_NOT_MATCHING: 'AUTH-002',
};
